### ISSUE TITLE
SQL NULL value becomes zero

### ISSUE THREAD

**Issue by tsubaki7737** [shinji19/embulk-input-athena#8]
@shinji19 Hello. I report an issue. Do you think about this?

### phenomenon
When I use long, double and boolean type,
PrestoSQL(Athena) NULL Value becomes zero in embulk .

I expect PrestoSQL NULL Value become null.

### cause
AthenaInputPlugin uses java.sql.ResultSet#getLong (getDouble, getBoolean, as well).

https://github.com/shinji19/embulk-input-athena/blob/develop/src/main/java/org/embulk/input/athena/AthenaInputPlugin.java#L158

getLong method returns 0 if value is SQL NULL.

> Returns:
> the column value; if the value is SQL NULL, the value returned is 0

https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#getLong-int-

### suggestion
I suggest AthenaInputPlugin to check SQL NULL with `wasNull()` method.  
When wasNull method return true, input NULL in embulk.

**Comment by shinji19** [comment]
@tsubaki0102 Thank you for  great issue!

I know
>getLong method returns 0 if value is SQL NULL.

by this issue at first time.

>I suggest AthenaInputPlugin to check SQL NULL with wasNull() method.
When wasNull method return true, input NULL in embulk.

I'll fix it like that. Additionally, I add an option like null_to_zero (default false) for convenience.

**Comment by tsubaki7737** [comment]
@shinji19 Thank you for quick response!
I hope it be fixed. :D

**Comment by shinji19** [comment]
@tsubaki0102 
fixed!
https://github.com/shinji19/embulk-input-athena/commit/0505cd1b1c219b59ffc9ad673e14a07fa75b9374

**Comment by tsubaki7737** [comment]
@shinji19 thank you! 🎉
